### ISSUE TITLE
a wheel would allow me to put it in the same requirement.txt file as numpy

### ISSUE THREAD

**Issue by stonebig** [PierreRaybaut/python-qwt#10]
I whish a wheel, otherwise pip will try to compile it into a wheel without keeping the order in the requirement.txt file, and fail because numpy is not yet installed. and so I need 2 requirements files

**Comment by PierreRaybaut** [comment]
Ok. Do you mean that you need that I upload a wheel package in PyPI? Can I upload both (.zip and wheel) or is it an issue somehow?

**Comment by stonebig** [comment]
You shall do both, as I think it's the best practice. By default, pip select the wheel when available

**Comment by PierreRaybaut** [comment]
Done!

**Comment by stonebig** [comment]
thanks !
