### ISSUE TITLE
Fix license and copyright [ part 2 ]

### ISSUE THREAD

**Issue by uwerat** [PierreRaybaut/python-qwt#11]
Hi Pierre,

a)
I can see, that you have corrected the license information, but you still have not added the copyright information. It has to be done in a similar way as you did it with the copyright in your files. The missing information has to be: "Copyright (C) 2002   Uwe Rathmann".

b) The files README and LICENSE are lacking the copyright information as well
c) The wrong information of setup.py needs to be fixed.
d) I didn't check all of the code - please do it carefully, when there is more time.

e)
I still expect, that you do release another alpha version with a correct license/copyright a.s.a.p. Packages on 3rd party pages like https://ftp-master.debian.org/new/python-qwt_6.1.2~a3-1~exp1.html have to disappear !

Please contact the debian maintainer and take care, that license and copyright information gets fixed in the meta information of the package too.

( I'm not sure if having 2 different licenses for the same package is supported by distributors like debian. If not you have to find a way how to express that the intersection between both licenses is the relevant information for the user. It might be easier to have only one license but keeping different copyrights - but of course this is up to you to decide. )

f)
Concerning guiqwt: this project gets linked against code that is published under the Qwt license and of course you have to respect all its paragraphs for this use case. This is not different to what you have to obtain, when linking against the C++ version.

When believing in "there is absolutely no license propagation or whatsover" please make yourself clear that you are wrong and better double check not doing things incorrect there too.

ciao,
Uwe

**Comment by picca** [comment]
Hello, debian packager here.

I am preparing the alpha4 version, but the QwtLicense is not distributed in the sources.
can you add it for the next alpha5.

for the e) point I will ask for deletion of the package from ftp-master.
also this is not an issue if some files has different license terms if at the end the final result is legal.
MIT + GPL = GPL
MIT + LGPL = MIt + LGPL :)

**Comment by picca** [comment]
PS: I will wait until you both agreed that the license things is ok before an upload to Debian.

thanks

**Comment by PierreRaybaut** [comment]
a) Done.
b) Done.
c) Is the setup.py a translation from Qwt C++ library? No. So it doesn't apply. As well as in the qwt.qt subpackage.
e) See comments from Frederic;
f) There is no linking between guiqwt and qwt, so we agree.

**Comment by picca** [comment]
@uwerat just for me ca nyou explain what is the purpose of the QwtLicense compare to the pure LGPL-2.1 version . this is a real question, I try to understand your point.

the point 2) of the QwtLicense is relevant for C/C++ library, but I do not see the point for pure python core where static and share doesn't mean anything.

**Comment by uwerat** [comment]
@picca:

This issue is not about finding a license for some code - it is about indicating the copyright/license it has.

If the Qwt license makes much sense in a python context is of course questionable, but using plain LGPL requires changing the license, what is everything else than an trivial step - considering, that Qwt exists since the 90s.

**Comment by picca** [comment]
@uwerat I do not want to change the license, I would like to understand why the Qwt license was created since LGPL was already available. this is just for my record

Cheers

**Comment by uwerat** [comment]
The Qwt license is derived from the LGPL with exceptions and of course those exceptions are the reason behind creating it.

The idea behind those exceptions is, that a user is allowed to link a closed source application statically without having to show application code. But then the usage of Qwt is not visible to the public anymore and the application it is required to indicate it "somehow else".

When talking about python the Qwt license also allows to hide code in some sort of blob without having to show your code. Please don't push me for proving my statement - but it should be clear, that a lawyer could easily explain that th term "linkage" covers more than using ld.

ciao,
Uwe
