### ISSUE TITLE
examples [take 2] :)

### ISSUE THREAD

**Issue by picca** [PierreRaybaut/python-qwt#12]
It seems that examples are not distributed witheh alpha 4 pypi sources ;)

**Comment by PierreRaybaut** [comment]
Damn :grin:
I've just moved the examples folder in qwt package which is a bad, bad idea :confounded:

(yes, and I have also opened the [Emoji cheat sheet](http://www.emoji-cheat-sheet.com/) for GitHub :smile:)

I'll fix it in the next alpha release.

**Comment by picca** [comment]
except if you want to provide a qwt-tests at the end, like you did for guidata and guiqwt.
Really nice feature to convince peoples to use your modules.

**Comment by PierreRaybaut** [comment]
Maybe in the future, but for now I'm just including the examples folder in souce package.
For me, the real demo of qwt is guiqwt!

Done in v6.1.2a6.
