### ISSUE TITLE
license copyright for the python translation ?

### ISSUE THREAD

**Issue by picca** [PierreRaybaut/python-qwt#13]
Hello Pierre,

Indeed you put Uwe in the copyright BUT you forget to put yourself or the CEA, I do not know excalty how the job was done. but someone did the python translation code and own the copyright for this work

I also saw that in the MIT license headers you refere to  spyderlib/__init__ which is not part of the sources.

another minor issue, is the reference to qwt/License in the Qwt header snipset

to my opinion the top level LICENSe file is enought and avoid other spyderlib, qwt etc.. LICENSe files.
this way it is a lot easyer to do cut and past from one project to the other :)

thanks

Frederic

**Comment by PierreRaybaut** [comment]
You're perfectly right!

So here is a proof that I'm really so philantropic that I forget to leave my footprint (un p'tit clin d'oeil à l'autre coincé du bulbe ;-)).

This is fixed in v6.1.2a6.
