### ISSUE TITLE
please add the long description in the setup.py

### ISSUE THREAD

**Issue by picca** [PierreRaybaut/python-qwt#2]
Hello, on Debian/Ubuntu/... we are using the setup.py informations in order to automatically generate the packaging.
The software use for this is python-stdeb
For now the long description is missing.
It would be nice if you could set the long description for us.

It seems also that the license is not catched also
the current PKG-INFO contain a bunch of UNKNOWN fieslds

Metadata-Version: 1.1
Name: qwt
Version: 6.1.2a3
Summary: qwt is a pure Python implementation of Qwt C++ library, using PyQt and NumPy
Home-page: UNKNOWN
Author: Pierre Raybaut
Author-email: pierre.raybaut@gmail.com
License: UNKNOWN
Description: UNKNOWN
Platform: UNKNOWN
Classifier: Topic :: Scientific/Engineering
Classifier: Development Status :: 3 - Alpha
Classifier: Operating System :: MacOS
Classifier: Operating System :: Microsoft :: Windows
Classifier: Operating System :: OS Independent
Classifier: Operating System :: POSIX
Classifier: Operating System :: Unix
Classifier: Programming Language :: Python :: 2.6
Classifier: Programming Language :: Python :: 2.7
Classifier: Programming Language :: Python :: 3
Requires: PyQt4 (>4.3)

The Requieres fields seems to be inconsistant with the one from the README
PyQT4 (>= 4.4) or PyQt5 (>= 5.5)

Cheers

**Comment by picca** [comment]
I am using this part as long description, but I do not know if this is what you want :)

 The qwt package is a pure Python implementation of Qwt C++ library
 with the following limitations.
 .
 The following `Qwt` classes won't be reimplemented in `qwt` because most 
 powerful features already exist in `guiqwt`:
   * QwtPlotZoomer
   * QwtCounter
   * QwtEventPattern
   * QwtPicker
   * QwtPlotPicker
 .
 QwtClipper is not implemented yet (and it will probably be very
 difficult or impossible to implement it in pure Python without
 performance issues).  As a consequence, when zooming in a plot curve,
 the entire curve is still painted (in other words, when working with
 large amount of data, there is no performance gain when zooming in).

**Comment by PierreRaybaut** [comment]
When PR https://github.com/PierreRaybaut/python-qwt/pull/5 will be merged (very soon). All missing metadata will be present in setup.py (long description, license, ...).
