### ISSUE TITLE
error in the scripts part

### ISSUE THREAD

**Issue by picca** [PierreRaybaut/python-qwt#21]
creating build/scripts-2.7
error: file '/home/picca/Debian/python-qwt/python-qwt/scripts/python-tests' does not exist
E: pybuild pybuild:262: build: plugin distutils failed with: exit code=1: /usr/bin/python setup.py build 

indeed tsetup.py comtain python-tests instead of python-qwt-tests

**Comment by PierreRaybaut** [comment]
Fixed.

Thanks @picca for reporting this... any other blocking issue?
If not, I'll upload the v0.1.1 release fixing this issue.

**Comment by picca** [comment]
no it is ok, it is just that now I am waiting for the doc ;), just kiding

**Comment by PierreRaybaut** [comment]
That's because you haven't read the release notes: "There is still work to do" :smile:
