### ISSUE TITLE
please add the doc and examples on pypi

### ISSUE THREAD

**Issue by picca** [PierreRaybaut/python-qwt#3]
Will it be possible for you to add the examples and the doc to the source zip distributed on pypi ?

**Comment by PierreRaybaut** [comment]
Unfortunately there is no documentation for now. But I will do something about it in the near future.

Regarding the examples, indeed they should be included in the distributed source package. I'll close this issue as soon as it's done.

**Comment by PierreRaybaut** [comment]
Done in v6.1.2a4
